# https://docs.microsoft.com/azure/devops/pipelines/languages/python
jobs:
- job: 'Style'
  pool:
    mvImage: 'VS2017-Win2016'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install black
        black --check src

- job: 'Test_Windows_x64'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 3
    
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
    
    - script: |
        python -m pip install tox
        tox -e py
      displayName: 'Test with tox & pytest'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version) x64 Windows'  
        
    - script: 'tox -e build'
      displayName: 'Build package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact: dist'
      inputs:
        pathtoPublish: 'dist'
        artifactName: 'dist'
